editor: visual

affiliations: []
brand: "brand.yml"
resources:
  - static
  - images
lightbox: true
format:
  html:
    comments:
      hypothesis: true
    grid:
      margin-width: 75px
      sidebar-width: 235px
    page-layout: article
    theme: [brand, baselineStyles.scss, accessStyles.scss]
    embed-resources: true
    self-contained: true
    toc: true
    toc-location: left
    toc-title: Table of Contents
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    title-block-banner: true
    title-block-categories: true
    fig-responsive: true

